### ISSUE TITLE
Ollama Not detecting NVIDIA GPU

### ISSUE THREAD

**Issue by sixshakybones** [otwld/ollama-helm#88]
### What happened?

Unable to get ollama to use the GPU for processing, I am following the guide [provided](https://github.com/otwld/ollama-helm), 
Pod log attached below, not detecting GPU but running fine
![image](https://github.com/user-attachments/assets/50ea1ac6-0585-4443-962e-fdf3f6c54052)
![image](https://github.com/user-attachments/assets/9622f03e-e8ff-4a4e-9430-a31ee0c430ac)

Running the following inside the container works: 
`kubectl exec My-Ollama-POD -c ollama -n ollama-helm -- nvidia-smi`

and produces the output:
![image](https://github.com/user-attachments/assets/c9f19f49-b6aa-4b8e-9b74-a201d808a13d)

Kubernetes is running on a baremetal server,` nvidia-smi && nvcc --version`: 
![image](https://github.com/user-attachments/assets/4d20dbaa-24ac-4fd7-afc1-4b27f70f42ae)
![image](https://github.com/user-attachments/assets/abeec818-1105-4bdd-88d5-53b46e7f8afd)

I can run the CUDA test from nvidia just fine and the GPU frequency increases when the container executes

### Chart version

0.53.0

### Kubernetes version

1.29.1

### Kubernetes distribution

 https://pkgs.k8s.io/core:/stable:/v1.29/deb

### Relevant log output

```shell
Couldn't find '/root/.ollama/id_ed25519'. Generating new private key.
Your new public key is: 

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIw/+NiCWNAi21tFQaSaQ4tFBL4bOQHLEVc41fBZe1t2

2024/08/16 15:27:06 routes.go:1125: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-08-16T15:27:06.281Z level=INFO source=images.go:782 msg="total blobs: 0"
time=2024-08-16T15:27:06.281Z level=INFO source=images.go:790 msg="total unused blobs removed: 0"
time=2024-08-16T15:27:06.282Z level=INFO source=routes.go:1172 msg="Listening on [::]:11434 (version 0.3.6)"
time=2024-08-16T15:27:06.282Z level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama3429065782/runners
time=2024-08-16T15:27:21.637Z level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu_avx cpu_avx2 cuda_v11 rocm_v60102 cpu]"
time=2024-08-16T15:27:21.637Z level=INFO source=gpu.go:204 msg="looking for compatible GPUs"
time=2024-08-16T15:27:21.637Z level=WARN source=gpu.go:226 msg="CPU does not have minimum vector extensions, GPU inference disabled" required=avx detected="no vector extensions"
time=2024-08-16T15:27:21.637Z level=INFO source=types.go:105 msg="inference compute" id=0 library=cpu compute="" driver=0.0 name="" total="70.7 GiB" available="67.6 GiB"
[GIN] 2024/08/16 - 15:27:21 | 200 |      75.703µs |       127.0.0.1 | HEAD     "/"
time=2024-08-16T15:27:24.508Z level=INFO source=download.go:175 msg="downloading 04778965089b in 17 100 MB part(s)"
time=2024-08-16T15:29:47.091Z level=INFO source=download.go:175 msg="downloading 7908abcab772 in 1 1.0 KB part(s)"
time=2024-08-16T15:29:49.484Z level=INFO source=download.go:175 msg="downloading 774a15e6f1e5 in 1 77 B part(s)"
time=2024-08-16T15:29:51.911Z level=INFO source=download.go:175 msg="downloading 3188becd6bae in 1 132 B part(s)"
time=2024-08-16T15:29:54.216Z level=INFO source=download.go:175 msg="downloading 0b8127ddf5ee in 1 42 B part(s)"
time=2024-08-16T15:29:56.647Z level=INFO source=download.go:175 msg="downloading 4ce4b16d33a3 in 1 555 B part(s)"
[GIN] 2024/08/16 - 15:30:13 | 200 |         2m51s |       127.0.0.1 | POST     "/api/pull"
[GIN] 2024/08/16 - 15:30:15 | 200 |      55.923µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:15 | 200 |      43.303µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:15 | 200 |        39.3µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:15 | 200 |      60.155µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:16 | 404 |       13.22µs |   172.21.59.100 | GET      "/favicon.ico"
[GIN] 2024/08/16 - 15:30:20 | 200 |      44.807µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:25 | 200 |      58.349µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:25 | 200 |      42.145µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:30 | 200 |      67.091µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:35 | 200 |      43.514µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:35 | 200 |      37.152µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:40 | 200 |      42.842µs |   172.21.59.100 | GET      "/"
time=2024-08-16T15:30:41.254Z level=INFO source=memory.go:309 msg="offload to cpu" layers.requested=-1 layers.model=33 layers.offload=0 layers.split="" memory.available="[67.6 GiB]" memory.required.full="4.6 GiB" memory.required.partial="0 B" memory.required.kv="2.5 GiB" memory.required.allocations="[4.6 GiB]" memory.weights.total="3.8 GiB" memory.weights.repeating="3.7 GiB" memory.weights.nonrepeating="102.8 MiB" memory.graph.full="548.0 MiB" memory.graph.partial="543.0 MiB"
time=2024-08-16T15:30:41.257Z level=INFO source=server.go:393 msg="starting llama server" cmd="/tmp/ollama3429065782/runners/cpu/ollama_llama_server --model /root/.ollama/models/blobs/sha256-04778965089b91318ad61d0995b7e44fad4b9a9f4e049d7be90932bf8812e828 --ctx-size 8192 --batch-size 512 --embedding --log-disable --no-mmap --numa distribute --parallel 4 --port 36861"
time=2024-08-16T15:30:41.257Z level=INFO source=sched.go:445 msg="loaded runners" count=1
time=2024-08-16T15:30:41.257Z level=INFO source=server.go:593 msg="waiting for llama runner to start responding"
time=2024-08-16T15:30:41.258Z level=INFO source=server.go:627 msg="waiting for server to become available" status="llm server error"
WARNING: /proc/sys/kernel/numa_balancing is enabled, this has been observed to impair performance
INFO [main] build info | build=1 commit="1e6f655" tid="138004461737856" timestamp=1723822241
INFO [main] system info | n_threads=8 n_threads_batch=-1 system_info="AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="138004461737856" timestamp=1723822241 total_threads=8
INFO [main] HTTP server listening | hostname="127.0.0.1" n_threads_http="7" port="36861" tid="138004461737856" timestamp=1723822241
llama_model_loader: loaded meta data with 20 key-value pairs and 325 tensors from /root/.ollama/models/blobs/sha256-04778965089b91318ad61d0995b7e44fad4b9a9f4e049d7be90932bf8812e828 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = phi2
llama_model_loader: - kv   1:                               general.name str              = Phi2
llama_model_loader: - kv   2:                        phi2.context_length u32              = 2048
llama_model_loader: - kv   3:                      phi2.embedding_length u32              = 2560
llama_model_loader: - kv   4:                   phi2.feed_forward_length u32              = 10240
llama_model_loader: - kv   5:                           phi2.block_count u32              = 32
llama_model_loader: - kv   6:                  phi2.attention.head_count u32              = 32
llama_model_loader: - kv   7:               phi2.attention.head_count_kv u32              = 32
llama_model_loader: - kv   8:          phi2.attention.layer_norm_epsilon f32              = 0.000010
llama_model_loader: - kv   9:                  phi2.rope.dimension_count u32              = 32
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,51200]   = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,51200]   = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  15:                      tokenizer.ggml.merges arr[str,50000]   = ["Ġ t", "Ġ a", "h e", "i n", "r e",...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 50256
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 50256
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 50256
llama_model_loader: - kv  19:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  195 tensors
llama_model_loader: - type q4_0:  129 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: missing or unrecognized pre-tokenizer type, using: 'default'
llm_load_vocab: special tokens cache size = 944
time=2024-08-16T15:30:41.509Z level=INFO source=server.go:627 msg="waiting for server to become available" status="llm server loading model"
llm_load_vocab: token to piece cache size = 0.3151 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = phi2
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 51200
llm_load_print_meta: n_merges         = 50000
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 2048
llm_load_print_meta: n_embd           = 2560
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_rot            = 32
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 80
llm_load_print_meta: n_embd_head_v    = 80
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 2560
llm_load_print_meta: n_embd_v_gqa     = 2560
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 10240
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 2048
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 3B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 2.78 B
llm_load_print_meta: model size       = 1.49 GiB (4.61 BPW) 
llm_load_print_meta: general.name     = Phi2
llm_load_print_meta: BOS token        = 50256 '<|endoftext|>'
llm_load_print_meta: EOS token        = 50256 '<|endoftext|>'
llm_load_print_meta: UNK token        = 50256 '<|endoftext|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 50256 '<|endoftext|>'
llm_load_print_meta: max token length = 256
llm_load_tensors: ggml ctx size =    0.15 MiB
llm_load_tensors:        CPU buffer size =  1526.50 MiB
llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =  2560.00 MiB
llama_new_context_with_model: KV self size  = 2560.00 MiB, K (f16): 1280.00 MiB, V (f16): 1280.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.82 MiB
llama_new_context_with_model:        CPU compute buffer size =   563.01 MiB
llama_new_context_with_model: graph nodes  = 1225
llama_new_context_with_model: graph splits = 1
[GIN] 2024/08/16 - 15:30:45 | 200 |       44.12µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:45 | 200 |      20.452µs |   172.21.59.100 | GET      "/"
INFO [main] model loaded | tid="138004461737856" timestamp=1723822246
time=2024-08-16T15:30:46.993Z level=INFO source=server.go:627 msg="waiting for server to become available" status="llm server not responding"
time=2024-08-16T15:30:47.245Z level=INFO source=server.go:632 msg="llama runner started in 5.99 seconds"
[GIN] 2024/08/16 - 15:30:50 | 200 |      51.367µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:54 | 500 | 12.874715525s |   172.21.59.100 | POST     "/api/generate"
[GIN] 2024/08/16 - 15:30:55 | 200 |      38.477µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:30:55 | 200 |      51.234µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:31:00 | 200 |      39.345µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:31:05 | 200 |      49.965µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:31:05 | 200 |      38.725µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:31:10 | 200 |      44.577µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:31:15 | 200 |      40.101µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:31:15 | 200 |     133.636µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:31:20 | 200 |      73.271µs |   172.21.59.100 | GET      "/"
[GIN] 2024/08/16 - 15:31:25 | 200 |      45.537µs |   172.21.59.100 | GET      "/"
```

### Your values.yaml

```yaml
ollama:
  gpu:
    # -- Enable GPU integration
    enabled: true

    # -- GPU type: 'nvidia' or 'amd'
    type: 'nvidia'

    # -- Specify the number of GPU to 1
    number: 1

  # -- List of models to pull at container startup
  models:
    - phi
```

**Comment by jdetroyes** [comment]
Hello @sixshakybones.

Can you enable debug on ollama by adding this line:

```yaml
extraEnv:
  - name: OLLAMA_DEBUG
    value: "1"
```

**Comment by rick-github** [comment]
```
time=2024-08-16T15:27:21.637Z level=WARN source=gpu.go:226 msg="CPU does not have minimum vector extensions, GPU inference disabled" required=avx detected="no vector extensions"
```
What's the output of `cat /proc/cpuinfo`?

**Comment by sixshakybones** [comment]
Hi,

Sorry for the delayed response, so I managed to find a workaround for now, we are actually testing this out on some older hardware, not really realizing that the CPU age would be a factor, there was a nifty workaround posted [here](https://github.com/ollama/ollama/issues/2187) on GitHub.

The gist of it is to remove the check for AVX compatibility and add CPU flags in source, rebuild and deploy and it works great for now.

**Comment by myusuf3** [comment]
> I am runnning into this same issue, it doesn'te ven try to load gpu

it was a driver issue and the version of ollama.
